apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: generic-qm
spec:
  queueManager:
    name: SENDER_UAT
    mqsc:
      - configMap:
          name: sender-uat-static-mqsc-configmap
          items:
            - static-qm.mqsc
    ini:
      - configMap:
          name: sender-uat-static-ini-configmap
          items:
            - qm.ini
  pki:
    keys:
      - name: sender
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: sender-uat-cert
    trust:
      - secret:
          items:
            - tls.crt
          secretName: receiver-uat-cert
        name: receiver
  template:
    pod:
      volumes:
        - name: config-volume-scripts
          configMap:
            name: sender-uat-scripts-configmap
            defaultMode: 0777
        - name: dynamic-config-volume-mqsc
          configMap:
            name: sender-uat-dynamic-mqsc-configmap
            defaultMode: 0777

  web:
    enabled: true
