apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sender-qm-to-qm-traffic
spec:
  # SENDER.EXT.CONN
  host: sender2e-ext2e-conn.chl.mq.ibm.com
  to:
    kind: Service
    name: sender-uat-qm-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
