apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: generic-qm
spec:
  queueManager:
    name: RECEIVER_UAT
    ini:
      - configMap:
          name: receiver-uat-static-ini-configmap
          items:
            - qm.ini
    mqsc:
      - configMap:
          name: receiver-uat-static-mqsc-configmap
          items:
            - static-qm.mqsc
     
  pki:
    keys:
      - name: receiver
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: receiver-uat-cert
    trust:
      - secret:
          items:
            - tls.crt
          secretName: sender-uat-cert
        name: sender
  template:
    pod:
      volumes:
        - name: config-volume-scripts
          configMap:
            name: receiver-uat-scripts-configmap
            defaultMode: 0777
        - name: dynamic-config-volume-mqsc
          configMap:
            name: receiver-uat-dynamic-mqsc-configmap
            defaultMode: 0777

  web:
    enabled: true
