apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: generic-qm
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
    use: Production
  queueManager:
    name: PRDQM01
