apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: generic-qm
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
    use: Production
  queueManager:
    name: PQM01
    mqsc:
      - configMap:
          name: qm01-mqsc-configmap
          items:
            # - static-generic.mqsc
            # - static-qm.mqsc
            - static-qm-prd.mqsc
  web:
    enabled: false
