apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: generic-qm
spec:
  queueManager:
    name: DQM02
    mqsc:
      - configMap:
          name: qm02-mqsc-configmap
          items:
            - static-generic.mqsc
            - static-qm.mqsc
            - static-qm-dev.mqsc

  web:
    enabled: true
