apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: generic-qm
spec:
  queueManager:
    name: DQM022
    mqsc:
      - configMap:
          name: qm022-static-mqsc-configmap
          items:
            - static-qm.mqsc
  pki:
    keys:
      - name: certificate
        secret:
          items:
            - tls.key
            - tls.crt
          secretName: qm022-cert
  template:
    pod:
      volumes:
        - name: config-volume-scripts
          configMap:
            name: qm022-scripts-configmap
            defaultMode: 0777
        - name: dynamic-config-volume-mqsc
          configMap:
            name: qm022-dynamic-mqsc-configmap
            defaultMode: 0777

  web:
    enabled: true
