apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: generic-qm
spec:
  license:
    accept: true
    license: L-RJON-C7QG3S
    use: NonProduction
  version: 9.2.4.0-r1

  queueManager:
    name: GENERIC
    image: cp.icr.io/cp/ibm-mqadvanced-server-integration:9.2.4.0-r1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    availability:
      type: NativeHA
    storage:
      defaultClass: ibmc-block-gold
      persistedData:
        class: ibmc-block-gold
        deleteClaim: true
        enabled: true
        type: persistent-claim
      queueManager:
        class: ibmc-block-gold
        deleteClaim: true
        type: persistent-claim
      recoveryLogs:
        class: ibmc-block-gold
        deleteClaim: true
        enabled: true
        type: persistent-claim
  template:
    pod:
      containers:
        - name: qmgr
          envFrom:
            - secretRef:
                name: mqsc-envs
          volumeMounts:
            - name: config-volume-scripts
              mountPath: /mq-config
              readOnly: true
            - name: dynamic-config-volume-mqsc
              mountPath: /dyn-mq-config-mqsc
              readOnly: true
