resources:
  - ../../base/qm01

patchesStrategicMerge:
  - ./qm.yaml

# Alternative mechanism for patching
patches:
  - target:
      group: mq.ibm.com
      kind: QueueManager
    patch: |-
      - op: add
        path: /spec/queueManager/image
        value: cp.icr.io/cp/ibm-mqadvanced-server-integration:9.2.4.0-r1
      - op: replace
        path: /metadata/name
        value: prdqm01
# Add envirnoment specific static MQSC such as channels and XMIT queues
configMapGenerator:
  - name: mqsc-configmap
    behavior: merge
    files:
      - static-qm-prd.mqsc
