resources:
  - ../../pte/qm02
  # - route.yaml # uncomment only if you want to change the SNI route

# patchesStrategicMerge:
#   - ./qm.yaml

# Alternative mechanism for patching
patches:
  - target:
      group: mq.ibm.com
      kind: QueueManager
    patch: |-
      - op: replace
        path: /metadata/name
        value: prdqm022

# # Add envirnoment specific static MQSC such as channels and XMIT queues
# configMapGenerator:
#   - name: mqsc-configmap
#     behavior: merge
#     files:
#       - static-qm-prd.mqsc
