apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ext-conn-prdqm02-traffic
spec:
  # EXT.CONN
  host: ext2e-conn.chl.mq.ibm.com
  to:
    kind: Service
    name: sender-uat-qm-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
